version: '3.1'

services:
  postgres:
    image: postgres:10
    container_name: my_postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - my_postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  volumes:
    my_postgres_data:/var/lib/postgresql